In [1]:
# importing libraries
import scipy.io as sio
import numpy as np  
import matplotlib.pyplot as plt
# import sys

# environmental settings
np.set_printoptions(threshold=1000) # adjust numbers to print out

In [9]:
# variable definition
N = 2           # total number of symbol
sps = 4         # number of samples in one symbol i.e. 1UI
SNR_db = 1000   # power ratio b/w signal and noise

In [86]:
# channel data generation
# N = 2; sps = 4
tx_data_digital = np.zeros((2,N))
tx_data_analog = np.zeros((2,N*sps))

for i in range(N):
    # random signal generation, either -1 or 1
    data = 2*np.random.randint(2, size=(2,1)) - 1
    tx_data_digital[:, i] = data.flatten()
    tx_data_analog[:, (i)*sps : (i+1)*sps] = np.repeat(data,sps,axis=1)

print(f'Tx analog data = \n{tx_data_analog}')
print(f'Tx digital data = \n{tx_data_digital}')

Tx analog data = 
[[-1. -1. -1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
Tx digital data = 
[[-1.  1.]
 [ 1.  1.]]


In [64]:
data = 2*np.random.randint(2, size=(2,1)) - 1
print(data.shape)
data = data.flatten()
print(data)

print(data.shape)
print(tx_data_digital[:,1].shape)

(2, 1)
[-1  1]
(2,)
(2,)
