In [48]:
# Delete all initialized variables in ipynb
%reset -f

In [49]:
import sys
import numpy as np

In [15]:
sz = sys.maxsize

scientific_notation="{:e}".format(sz)
print("Size of address space =", sz , "=" ,scientific_notation)

Size of address space = 9223372036854775807 = 9.223372e+18


In [20]:
arr = np.zeros(10 ** 13)
print(arr.dtype)
print("{:e}".format(sys.getsizeof(arr)))

del arr
arr = np.zeros(10 ** 13, dtype=np.int8)
print(arr.dtype)
print("{:e}".format(sys.getsizeof(arr)))

float64
8.000000e+13
int8
1.000000e+13


In [50]:
# del arr

arr_lst = []

arr1 = np.zeros(10 ** 14, dtype=np.uint8)
print(arr1)
print("{:e}".format(sys.getsizeof(arr1)))
arr_lst.append(arr1)
arr2 = np.zeros(10 ** 14, dtype=np.uint8)
print(arr2)
arr_lst.append(arr2)

[0 0 0 ... 0 0 0]
1.000000e+14


MemoryError: Unable to allocate 90.9 TiB for an array with shape (100000000000000,) and data type uint8

In [ ]:
np.zeros(10 ** 12)

MemoryError: Unable to allocate 7.28 TiB for an array with shape (1000000000000,) and data type float64

In [ ]:
np.zeros(10 ** 13)

MemoryError: Unable to allocate 72.8 TiB for an array with shape (10000000000000,) and data type float64

In [ ]:
.1+.1+.1 == .3

False

In [ ]:
import numpy as np

a = np.array([[-1],[1]])
print(a)
Tx = np.zeros((2,2), dtype=np.int)
print(Tx)
Tx[:,0] = a
print(Tx)

[[-1]
 [ 1]]
[[0 0]
 [0 0]]


/var/folders/m_/rv9nk6q90zjdt7nx4w1m4jt40000gn/T/ipykernel_36375/1850557817.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Tx = np.zeros((2,2), dtype=np.int)


ValueError: could not broadcast input array from shape (2,1) into shape (2,)